import { Member, KixLog } from './types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 1,
    name: 'Mendes Victor (Admin)',
    phone: '+244 923 000 000',
    email: 'lmendesvictor@gmail.com',
    avatarColor: 'bg-emerald-600',
    assignedMonth: 1,
    role: 'admin',
    tempPassword: 'Historia100',
    bankIban: 'AO06.0006.0001.0002.0003.0004.5',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
  {
    id: 2,
    name: 'Ana Paula Gouveia',
    phone: '+244 925 101 202',
    email: 'anapaula@gmail.com',
    avatarColor: 'bg-indigo-600',
    assignedMonth: 2,
    role: 'membro',
    tempPassword: 'anapaula123',
    bankIban: 'AO06.0006.0000.1234.5678.9012.3',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
  {
    id: 3,
    name: 'Carlos Alberto Silva',
    phone: '+244 912 303 404',
    email: 'carlos.alberto@hotmail.com',
    avatarColor: 'bg-amber-600',
    assignedMonth: 3,
    role: 'membro',
    tempPassword: 'carlos123',
    bankIban: 'AO06.0006.0000.9876.5432.1098.7',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
  {
    id: 4,
    name: 'Filomena da Costa',
    phone: '+244 931 505 606',
    email: 'filomena.costa@yahoo.com',
    avatarColor: 'bg-purple-600',
    assignedMonth: 4,
    role: 'membro',
    tempPassword: 'filomena123',
    bankIban: 'AO06.0040.0000.1111.2222.3333.4',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
  {
    id: 5,
    name: 'João Kiala',
    phone: '+244 924 707 808',
    email: 'joao.kiala@snl.co.ao',
    avatarColor: 'bg-pink-600',
    assignedMonth: 5,
    role: 'membro',
    tempPassword: 'joao123',
    bankIban: 'AO06.0055.0000.5555.6666.7777.8',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
  {
    id: 6,
    name: 'Teresa de Jesus',
    phone: '+244 945 909 010',
    email: 'teresa.jesus@gmail.com',
    avatarColor: 'bg-teal-600',
    assignedMonth: 6,
    role: 'membro',
    tempPassword: 'teresa123',
    bankIban: 'AO06.0011.0000.9999.8888.7777.6',
    contributions: {
      1: { paid: false },
      2: { paid: false },
      3: { paid: false },
      4: { paid: false },
      5: { paid: false },
      6: { paid: false },
    },
    benefits: {},
    socialSupportReceived: 0,
  },
];

export const INITIAL_LOGS: KixLog[] = [
  {
    id: 'log-initial',
    timestamp: new Date().toISOString(),
    type: 'cycle_change',
    amount: 0,
    description: 'Fundo de Poupança Kix-Fundo inicializado com sucesso para o ciclo operacional ativo.',
    month: 1,
  },
];
